version: '3.8'
services:
  chat-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8010"
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: chat_db
      DB_HOST: db
      DB_PORT: 5432
      LLM_API_URL: "http://10.32.15.90:8007/v1/chat/completions"
    volumes:
      - ./backend/data:/app/data

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chat-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    # ports:
    #   - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - chat-backend
    environment:
      - VITE_API_URL=http://chat-backend:8010
    command: npm run build

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
    depends_on:
      - chat-frontend
      - chat-backend

volumes:
  postgres_data:
