FROM python:3.10

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && pip install numpy==1.24.3
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m nltk.downloader punkt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8010"]
